### ISSUE TITLE
NonFungible Token requires the default feeCollector.

### ISSUE THREAD

**Issue by PandaTea** [maxonrow/maxonrow-go#204]
When I try to create an NFT token, mxwd throws the following error
```
'{"codespace":"sdk","code":7,"message":"Fee collector invalid."}'
```

so i created a interface for query feeCollector of NFT.
and the return is nil.

![image](https://user-images.githubusercontent.com/29042336/97796996-d2d57580-1c53-11eb-9e4e-291d46c5fb69.png)

So, I looked for the interface to set up the feeCollector.

![image](https://user-images.githubusercontent.com/29042336/97797022-44152880-1c54-11eb-8328-3d296f78666e.png)

I Found that SetFeeCollectorAddresses is only called in the MaintainerProposal

If the gov module does not create a corresponding Proposal, the user can never use the NFT token feature
Should we provide a default feeCollector for NFT by hard-coding ?

**Comment by b00f** [comment]
Maintainer module is in charge of setting Fee multiplier and fee collector. 

Default fee collector address can't be hard coded because it changes from chain to chain. 
Another place is adding default fee collector inside genesis. In this case we need to add a new parameter to genesis doc.

However the main reason we don't have any default value for fee_collector is to control the NFT/FT module. 
If the maintainer doesn't want to support NFT module, he simply he can let fee collector empty.

**Comment by yenkhoon** [comment]
@PandaTea This is a govern blockchain. If you were to test it out our nft, I suggest you run our test case in go test environment and copy that state and run the blockchain. The keys are stored inside the test folder as well. 

We do not hardcoded any addresses, because we practice the maintainers should take care of this. Also @b00f made a good statement about the reason.

Additionally, the maintainers module, is a module made for the governors base on the governing purposes. Any proposal made, it needs 3 agreements to be approved or rejected.

**Comment by PandaTea** [comment]
> @PandaTea This is a govern blockchain. If you were to test it out our nft, I suggest you run our test case in go test environment and copy that state and run the blockchain. The keys are stored inside the test folder as well.
> 
> We do not hardcoded any addresses, because we practice the maintainers should take care of this. Also @b00f made a good statement about the reason.
> 
> Additionally, the maintainers module, is a module made for the governors base on the governing purposes. Any proposal made, it needs 3 agreements to be approved or rejected.

thank you，i got it.

**Comment by PandaTea** [comment]
> Maintainer module is in charge of setting Fee multiplier and fee collector.
> 
> Default fee collector address can't be hard coded because it changes from chain to chain.
> Another place is adding default fee collector inside genesis. In this case we need to add a new parameter to genesis doc.
> 
> However the main reason we don't have any default value for fee_collector is to control the NFT/FT module.
> If the maintainer doesn't want to support NFT module, he simply he can let fee collector empty.

i got it, thanks for your answer
